[package]
name = "mnist"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = {git = "https://github.com/Pyrrhos512/Rust-matrix"}
byteorder = "1.4.3"
num-traits = "0.2.15"
plotters = "0.3.4"